import {
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconBell,
  IconBookmark,
  IconCalendar,
  IconCamera,
  IconCircleCheck,
  IconClock,
  IconCloud,
  IconDownload,
  IconExternalLink,
  IconEye,
  IconFile,
  IconFilter,
  IconFolder,
  IconHeart,
  IconHome,
  IconInfoCircle,
  IconLink,
  IconLock,
  IconMail,
  IconMapPin,
  IconMenu2,
  IconMessageCircle,
  IconMoon,
  IconMusic,
  IconPencil,
  IconPhoto,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSend,
  IconSettings,
  IconShare,
  IconStar,
  IconSun,
  IconTrash,
  IconUpload,
  IconUser,
  IconVolume,
  IconVolumeOff,
  IconX,
  IconPhone,
  IconLockOpen,
  IconAdjustmentsHorizontal,
  IconAlertTriangle,
  IconArchive,
  IconArrowBackUp,
  IconArrowForwardUp,
  IconArrowNarrowDown,
  IconArrowNarrowLeft,
  IconArrowNarrowRight,
  IconArrowNarrowUp,
  IconArrowsDiagonal,
  IconArrowsExchange,
  IconAt,
  IconAward,
  IconBolt,
  IconBuilding,
  IconCar,
  IconChartBar,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleMinus,
  IconCirclePlus,
  IconClipboard,
  IconCopy,
  IconCornerDownLeft,
  IconCornerDownRight,
  IconDashboard,
  IconDatabase,
  IconDeviceFloppy,
  IconDots,
  IconDotsVertical,
  IconFileDownload,
  IconFileText,
  IconFileUpload,
  IconFileZip,
  IconFolderMinus,
  IconFolderOpen,
  IconFolderPlus,
  IconHeadphones,
  IconHelpCircle,
  IconKey,
  IconLayoutGrid,
  IconList,
  IconLogin,
  IconLogout,
  IconMaximize,
  IconMicrophone,
  IconMicrophoneOff,
  IconMinimize,
  IconMovie,
  IconNotes,
  IconPalette,
  IconPaperclip,
  IconPhotoPlus,
  IconPlayerSkipBack,
  IconPlayerSkipForward,
  IconPlayerStop,
  IconPlaylist,
  IconPrinter,
  IconQrcode,
  IconRadio,
  IconShield,
  IconShoppingCart,
  IconTag,
  IconThumbUp,
  IconTool,
  IconUsers,
  IconVideo,
  IconWorld,
  IconZoomIn,
  IconZoomOut,
} from "@tabler/icons-react";
import { pathroomOriginalIcons } from "./icons/pathroom-originals/index.js";
import { batch002Catalog } from "./icons/pathroom-originals/batch-002-catalog.js";
import { batch003Catalog } from "./icons/pathroom-originals/batch-003-catalog.js";
import { batch004Catalog } from "./icons/pathroom-originals/batch-004-catalog.js";

export const collections = {
  tabler: {
    label: "Tabler Icons",
    licenseName: "MIT",
    publicLicenseUrl:
      "https://dreiachse-cyber.github.io/pathroom/THIRD_PARTY_NOTICES.txt",
    copyrightHolder: "Copyright (c) 2020-2026 Paweł Kuna",
    svgComment:
      "Tabler Icons v3.46.0 | MIT | Copyright (c) 2020-2026 Paweł Kuna",
  },
  "pathroom-originals": {
    label: "PATHROOM Originals",
    licenseName: "MIT",
    publicLicenseUrl:
      "https://dreiachse-cyber.github.io/pathroom/PATHROOM_ORIGINALS_LICENSE.txt",
    copyrightHolder: "Copyright (c) 2026 PATHROOM",
    svgComment: "PATHROOM Original | MIT | Copyright (c) 2026 PATHROOM",
  },
};

export const categories = [
  { id: "all", label: "すべて" },
  { id: "ui", label: "UI" },
  { id: "arrows", label: "矢印" },
  { id: "files", label: "ファイル" },
  { id: "media", label: "メディア" },
  { id: "commerce", label: "コマース" },
  { id: "communication", label: "コミュニケーション" },
  { id: "data", label: "データ" },
  { id: "devices", label: "デバイス" },
  { id: "maps", label: "地図" },
  { id: "time", label: "時間" },
];

export const originalsCatalog = [
  original(
    "sparkles",
    "Sparkles",
    "きらめき",
    "ui",
    ["magic", "shine", "AI", "装飾"],
  ),
  original(
    "layers",
    "Layers",
    "レイヤー",
    "ui",
    ["stack", "arrange", "重なり", "階層"],
  ),
  original(
    "drag-handle",
    "Drag Handle",
    "ドラッグハンドル",
    "ui",
    ["move", "reorder", "つかむ", "並べ替え"],
  ),
  original(
    "command-key",
    "Command Key",
    "コマンドキー",
    "ui",
    ["shortcut", "keyboard", "操作", "キー"],
  ),
  original(
    "contrast",
    "Contrast",
    "コントラスト",
    "ui",
    ["theme", "brightness", "明暗", "表示"],
  ),
  original(
    "focus-frame",
    "Focus Frame",
    "フォーカス枠",
    "ui",
    ["target", "scan", "選択", "注目"],
  ),
  original(
    "move-all",
    "Move All",
    "全方向へ移動",
    "arrows",
    ["drag", "direction", "移動", "四方向"],
  ),
  original(
    "turn-left",
    "Turn Left",
    "左折",
    "arrows",
    ["direction", "corner", "左", "曲がる"],
  ),
  original(
    "turn-right",
    "Turn Right",
    "右折",
    "arrows",
    ["direction", "corner", "右", "曲がる"],
  ),
  original(
    "route",
    "Route",
    "経路",
    "arrows",
    ["navigation", "path", "道順", "移動"],
  ),
  original(
    "branch",
    "Branch",
    "分岐",
    "arrows",
    ["split", "flow", "分かれる", "経路"],
  ),
  original(
    "merge",
    "Merge",
    "合流",
    "arrows",
    ["join", "flow", "まとまる", "経路"],
  ),
  original(
    "document-check",
    "Document Check",
    "確認済み文書",
    "files",
    ["approved", "done", "文書", "完了"],
  ),
  original(
    "document-search",
    "Document Search",
    "文書検索",
    "files",
    ["find", "inspect", "文書", "探す"],
  ),
  original(
    "folder-lock",
    "Folder Lock",
    "ロック付きフォルダ",
    "files",
    ["secure", "private", "フォルダ", "保護"],
  ),
  original(
    "inbox",
    "Inbox",
    "受信箱",
    "files",
    ["receive", "tray", "受信", "書類"],
  ),
  original(
    "package",
    "Package",
    "パッケージ",
    "files",
    ["box", "delivery", "荷物", "配布"],
  ),
  original(
    "cloud-sync",
    "Cloud Sync",
    "クラウド同期",
    "files",
    ["online", "refresh", "同期", "保存"],
  ),
  original(
    "waveform",
    "Waveform",
    "波形",
    "media",
    ["audio", "sound", "音声", "波"],
  ),
  original(
    "podcast",
    "Podcast",
    "ポッドキャスト",
    "media",
    ["broadcast", "voice", "配信", "音声"],
  ),
  original(
    "subtitles",
    "Subtitles",
    "字幕",
    "media",
    ["captions", "text", "テロップ", "動画"],
  ),
  original(
    "picture-in-picture",
    "Picture in Picture",
    "ピクチャーインピクチャー",
    "media",
    ["player", "window", "小窓", "動画"],
  ),
  original(
    "repeat",
    "Repeat",
    "リピート",
    "media",
    ["loop", "replay", "繰り返し", "再生"],
  ),
  original(
    "shuffle",
    "Shuffle",
    "シャッフル",
    "media",
    ["random", "mix", "ランダム", "再生"],
  ),
  ...batch002Catalog.map(
    ({ slug, name, nameJa, category, tags, createdAt, batch }) =>
      original(slug, name, nameJa, category, tags, createdAt, batch),
  ),
  ...batch003Catalog.map(
    ({ slug, name, nameJa, category, tags, createdAt, batch, family }) =>
      original(slug, name, nameJa, category, tags, createdAt, batch, family),
  ),
  ...batch004Catalog.map(
    ({ slug, name, nameJa, category, tags, createdAt, batch }) =>
      original(slug, name, nameJa, category, tags, createdAt, batch),
  ),
];

export const catalog = [
  icon("search", "Search", "検索", "ui", IconSearch, ["find", "探す", "虫眼鏡"], "2026-08-09"),
  icon("arrow-up", "Arrow Up", "上向き矢印", "arrows", IconArrowUp, ["up", "上", "方向"], "2026-08-09"),
  icon("folder", "Folder", "フォルダ", "files", IconFolder, ["directory", "書類", "保存"], "2026-08-09"),
  icon("bell", "Bell", "通知", "ui", IconBell, ["notification", "alert", "お知らせ"], "2026-08-09"),
  icon("user", "User", "ユーザー", "ui", IconUser, ["person", "account", "人物"], "2026-08-09"),
  icon("download", "Download", "ダウンロード", "arrows", IconDownload, ["save", "保存", "下向き"], "2026-08-09"),
  icon("home", "Home", "ホーム", "ui", IconHome, ["house", "top", "家"], "2026-08-08"),
  icon("settings", "Settings", "設定", "ui", IconSettings, ["gear", "config", "歯車"], "2026-08-08"),
  icon("mail", "Mail", "メール", "ui", IconMail, ["email", "message", "封筒"], "2026-08-08"),
  icon("calendar", "Calendar", "カレンダー", "ui", IconCalendar, ["date", "schedule", "日付"], "2026-08-08"),
  icon("trash", "Trash", "削除", "files", IconTrash, ["delete", "bin", "ゴミ箱"], "2026-08-08"),
  icon("edit", "Edit", "編集", "ui", IconPencil, ["pencil", "write", "鉛筆"], "2026-08-08"),
  icon("star", "Star", "スター", "ui", IconStar, ["favorite", "rate", "星"], "2026-08-07"),
  icon("heart", "Heart", "ハート", "ui", IconHeart, ["like", "favorite", "好き"], "2026-08-07"),
  icon("check-circle", "Check Circle", "チェック", "ui", IconCircleCheck, ["done", "success", "完了"], "2026-08-07"),
  icon("info-circle", "Info Circle", "情報", "ui", IconInfoCircle, ["information", "help", "案内"], "2026-08-07"),
  icon("menu", "Menu", "メニュー", "ui", IconMenu2, ["navigation", "hamburger", "一覧"], "2026-08-07"),
  icon("close", "Close", "閉じる", "ui", IconX, ["dismiss", "cancel", "取消"], "2026-08-07"),
  icon("arrow-down", "Arrow Down", "下向き矢印", "arrows", IconArrowDown, ["down", "下", "方向"], "2026-08-06"),
  icon("arrow-left", "Arrow Left", "左向き矢印", "arrows", IconArrowLeft, ["back", "previous", "左"], "2026-08-06"),
  icon("arrow-right", "Arrow Right", "右向き矢印", "arrows", IconArrowRight, ["next", "forward", "右"], "2026-08-06"),
  icon("upload", "Upload", "アップロード", "arrows", IconUpload, ["send", "上げる", "投稿"], "2026-08-06"),
  icon("file", "File", "ファイル", "files", IconFile, ["document", "paper", "書類"], "2026-08-06"),
  icon("bookmark", "Bookmark", "ブックマーク", "files", IconBookmark, ["save", "mark", "しおり"], "2026-08-06"),
  icon("clock", "Clock", "時計", "ui", IconClock, ["time", "history", "時間"], "2026-08-05"),
  icon("plus", "Add", "追加", "ui", IconPlus, ["plus", "new", "作成"], "2026-08-05"),
  icon("external-link", "External Link", "外部リンク", "arrows", IconExternalLink, ["open", "new window", "別画面"], "2026-08-05"),
  icon("link", "Link", "リンク", "ui", IconLink, ["url", "chain", "接続"], "2026-08-05"),
  icon("eye", "View", "表示", "ui", IconEye, ["preview", "visible", "見る"], "2026-08-05"),
  icon("lock", "Lock", "ロック", "ui", IconLock, ["secure", "private", "鍵"], "2026-08-05"),
  icon("unlock", "Unlock", "ロック解除", "ui", IconLockOpen, ["open", "public", "解錠"], "2026-08-04"),
  icon("camera", "Camera", "カメラ", "media", IconCamera, ["photo", "shoot", "撮影"], "2026-08-04"),
  icon("photo", "Photo", "画像", "media", IconPhoto, ["image", "picture", "写真"], "2026-08-04"),
  icon("music", "Music", "音楽", "media", IconMusic, ["audio", "song", "音"], "2026-08-04"),
  icon("play", "Play", "再生", "media", IconPlayerPlay, ["start", "video", "開始"], "2026-08-04"),
  icon("pause", "Pause", "一時停止", "media", IconPlayerPause, ["stop", "video", "休止"], "2026-08-04"),
  icon("volume", "Volume", "音量", "media", IconVolume, ["sound", "speaker", "音"], "2026-08-03"),
  icon("mute", "Mute", "ミュート", "media", IconVolumeOff, ["silent", "sound off", "消音"], "2026-08-03"),
  icon("cloud", "Cloud", "クラウド", "files", IconCloud, ["storage", "online", "保存"], "2026-08-03"),
  icon("sun", "Sun", "太陽", "ui", IconSun, ["light", "day", "昼"], "2026-08-03"),
  icon("moon", "Moon", "月", "ui", IconMoon, ["dark", "night", "夜"], "2026-08-03"),
  icon("map-pin", "Map Pin", "位置", "ui", IconMapPin, ["location", "place", "地図"], "2026-08-02"),
  icon("phone", "Phone", "電話", "ui", IconPhone, ["call", "contact", "通話"], "2026-08-02"),
  icon("message", "Message", "メッセージ", "ui", IconMessageCircle, ["chat", "comment", "会話"], "2026-08-02"),
  icon("send", "Send", "送信", "arrows", IconSend, ["submit", "mail", "送る"], "2026-08-02"),
  icon("share", "Share", "共有", "arrows", IconShare, ["send", "social", "シェア"], "2026-08-02"),
  icon("refresh", "Refresh", "更新", "arrows", IconRefresh, ["reload", "sync", "再読込"], "2026-08-01"),
  icon("filter", "Filter", "絞り込み", "ui", IconFilter, ["sort", "narrow", "条件"], "2026-08-01"),
  icon("adjustments", "Adjustments", "調整", "ui", IconAdjustmentsHorizontal, ["controls", "sliders", "設定"], "2026-08-01"),
  icon("alert-triangle", "Alert Triangle", "警告", "ui", IconAlertTriangle, ["warning", "danger", "注意"], "2026-08-01"),
  icon("at-sign", "At Sign", "アットマーク", "ui", IconAt, ["email", "mention", "宛先"], "2026-08-01"),
  icon("award", "Award", "受賞", "ui", IconAward, ["badge", "prize", "メダル"], "2026-08-01"),
  icon("bolt", "Bolt", "稲妻", "ui", IconBolt, ["flash", "energy", "高速"], "2026-08-01"),
  icon("building", "Building", "建物", "ui", IconBuilding, ["office", "company", "施設"], "2026-08-01"),
  icon("car", "Car", "車", "ui", IconCar, ["vehicle", "drive", "自動車"], "2026-08-01"),
  icon("chart-bar", "Chart Bar", "棒グラフ", "ui", IconChartBar, ["analytics", "stats", "集計"], "2026-07-31"),
  icon("circle-minus", "Minus Circle", "マイナス", "ui", IconCircleMinus, ["remove", "subtract", "減らす"], "2026-07-31"),
  icon("circle-plus", "Plus Circle", "プラス", "ui", IconCirclePlus, ["add", "create", "増やす"], "2026-07-31"),
  icon("copy", "Copy", "コピー", "ui", IconCopy, ["duplicate", "clone", "複製"], "2026-07-31"),
  icon("dashboard", "Dashboard", "ダッシュボード", "ui", IconDashboard, ["overview", "panel", "管理画面"], "2026-07-31"),
  icon("dots-horizontal", "More Horizontal", "その他・横", "ui", IconDots, ["menu", "ellipsis", "追加操作"], "2026-07-31"),
  icon("dots-vertical", "More Vertical", "その他・縦", "ui", IconDotsVertical, ["menu", "ellipsis", "追加操作"], "2026-07-31"),
  icon("help-circle", "Help Circle", "ヘルプ", "ui", IconHelpCircle, ["question", "support", "案内"], "2026-07-31"),
  icon("key", "Key", "鍵", "ui", IconKey, ["password", "access", "認証"], "2026-07-30"),
  icon("layout-grid", "Grid", "グリッド", "ui", IconLayoutGrid, ["layout", "tiles", "一覧"], "2026-07-30"),
  icon("list", "List", "リスト", "ui", IconList, ["rows", "items", "一覧"], "2026-07-30"),
  icon("login", "Login", "ログイン", "ui", IconLogin, ["sign in", "enter", "認証"], "2026-07-30"),
  icon("logout", "Logout", "ログアウト", "ui", IconLogout, ["sign out", "exit", "退出"], "2026-07-30"),
  icon("palette", "Palette", "パレット", "ui", IconPalette, ["color", "design", "配色"], "2026-07-30"),
  icon("printer", "Printer", "プリンター", "ui", IconPrinter, ["print", "paper", "印刷"], "2026-07-30"),
  icon("qr-code", "QR Code", "QRコード", "ui", IconQrcode, ["scan", "barcode", "読み取り"], "2026-07-30"),
  icon("shield", "Shield", "シールド", "ui", IconShield, ["security", "protect", "保護"], "2026-07-29"),
  icon("shopping-cart", "Shopping Cart", "カート", "ui", IconShoppingCart, ["shop", "commerce", "買い物"], "2026-07-29"),
  icon("tag", "Tag", "タグ", "ui", IconTag, ["label", "price", "分類"], "2026-07-29"),
  icon("thumbs-up", "Thumbs Up", "いいね", "ui", IconThumbUp, ["like", "approve", "評価"], "2026-07-29"),
  icon("tools", "Tools", "ツール", "ui", IconTool, ["repair", "utility", "道具"], "2026-07-29"),
  icon("users", "Users", "ユーザー一覧", "ui", IconUsers, ["people", "group", "複数人"], "2026-07-29"),
  icon("world", "World", "世界", "ui", IconWorld, ["globe", "language", "地球"], "2026-07-29"),
  icon("zoom-in", "Zoom In", "拡大", "ui", IconZoomIn, ["magnify", "scale", "大きく"], "2026-07-28"),
  icon("zoom-out", "Zoom Out", "縮小", "ui", IconZoomOut, ["reduce", "scale", "小さく"], "2026-07-28"),
  icon("expand", "Expand", "拡張", "arrows", IconArrowsDiagonal, ["resize", "diagonal", "広げる"], "2026-07-28"),
  icon("swap", "Swap", "入れ替え", "arrows", IconArrowsExchange, ["exchange", "switch", "交換"], "2026-07-28"),
  icon("undo", "Undo", "元に戻す", "arrows", IconArrowBackUp, ["back", "revert", "取消"], "2026-07-28"),
  icon("redo", "Redo", "やり直す", "arrows", IconArrowForwardUp, ["forward", "repeat", "再実行"], "2026-07-28"),
  icon("arrow-narrow-down", "Narrow Arrow Down", "細い下向き矢印", "arrows", IconArrowNarrowDown, ["down", "direction", "下"], "2026-07-28"),
  icon("arrow-narrow-left", "Narrow Arrow Left", "細い左向き矢印", "arrows", IconArrowNarrowLeft, ["left", "direction", "戻る"], "2026-07-27"),
  icon("arrow-narrow-right", "Narrow Arrow Right", "細い右向き矢印", "arrows", IconArrowNarrowRight, ["right", "direction", "進む"], "2026-07-27"),
  icon("arrow-narrow-up", "Narrow Arrow Up", "細い上向き矢印", "arrows", IconArrowNarrowUp, ["up", "direction", "上"], "2026-07-27"),
  icon("chevron-down", "Chevron Down", "下向き山形", "arrows", IconChevronDown, ["down", "expand", "開く"], "2026-07-27"),
  icon("chevron-left", "Chevron Left", "左向き山形", "arrows", IconChevronLeft, ["left", "previous", "戻る"], "2026-07-27"),
  icon("chevron-right", "Chevron Right", "右向き山形", "arrows", IconChevronRight, ["right", "next", "進む"], "2026-07-27"),
  icon("chevron-up", "Chevron Up", "上向き山形", "arrows", IconChevronUp, ["up", "collapse", "閉じる"], "2026-07-27"),
  icon("corner-down-left", "Corner Down Left", "左下へ折れる矢印", "arrows", IconCornerDownLeft, ["return", "enter", "改行"], "2026-07-27"),
  icon("corner-down-right", "Corner Down Right", "右下へ折れる矢印", "arrows", IconCornerDownRight, ["turn", "reply", "折り返し"], "2026-07-26"),
  icon("maximize", "Maximize", "最大化", "arrows", IconMaximize, ["fullscreen", "expand", "拡大"], "2026-07-26"),
  icon("minimize", "Minimize", "最小化", "arrows", IconMinimize, ["collapse", "shrink", "縮小"], "2026-07-26"),
  icon("archive", "Archive", "アーカイブ", "files", IconArchive, ["box", "store", "保管"], "2026-07-26"),
  icon("clipboard", "Clipboard", "クリップボード", "files", IconClipboard, ["paste", "copy", "貼り付け"], "2026-07-26"),
  icon("file-text", "Text File", "テキストファイル", "files", IconFileText, ["document", "text", "文書"], "2026-07-26"),
  icon("file-download", "Download File", "ファイルをダウンロード", "files", IconFileDownload, ["document", "save", "取得"], "2026-07-26"),
  icon("file-upload", "Upload File", "ファイルをアップロード", "files", IconFileUpload, ["document", "send", "投稿"], "2026-07-26"),
  icon("file-zip", "ZIP File", "ZIPファイル", "files", IconFileZip, ["archive", "compressed", "圧縮"], "2026-07-25"),
  icon("folder-open", "Open Folder", "開いたフォルダ", "files", IconFolderOpen, ["directory", "browse", "参照"], "2026-07-25"),
  icon("folder-plus", "Add Folder", "フォルダを追加", "files", IconFolderPlus, ["directory", "new", "作成"], "2026-07-25"),
  icon("folder-minus", "Remove Folder", "フォルダを削除", "files", IconFolderMinus, ["directory", "remove", "除外"], "2026-07-25"),
  icon("paperclip", "Attachment", "添付", "files", IconPaperclip, ["attach", "file", "クリップ"], "2026-07-25"),
  icon("notes", "Notes", "ノート", "files", IconNotes, ["memo", "document", "メモ"], "2026-07-25"),
  icon("database", "Database", "データベース", "files", IconDatabase, ["storage", "server", "保存"], "2026-07-25"),
  icon("save", "Save", "保存", "files", IconDeviceFloppy, ["floppy", "store", "記録"], "2026-07-25"),
  icon("video", "Video", "ビデオ", "media", IconVideo, ["movie", "camera", "映像"], "2026-07-24"),
  icon("microphone", "Microphone", "マイク", "media", IconMicrophone, ["voice", "record", "音声"], "2026-07-24"),
  icon("microphone-off", "Microphone Off", "マイクオフ", "media", IconMicrophoneOff, ["mute", "voice", "消音"], "2026-07-24"),
  icon("headphones", "Headphones", "ヘッドホン", "media", IconHeadphones, ["audio", "listen", "音楽"], "2026-07-24"),
  icon("stop", "Stop", "停止", "media", IconPlayerStop, ["player", "square", "止める"], "2026-07-24"),
  icon("skip-forward", "Skip Forward", "次へスキップ", "media", IconPlayerSkipForward, ["next", "player", "早送り"], "2026-07-24"),
  icon("skip-back", "Skip Back", "前へスキップ", "media", IconPlayerSkipBack, ["previous", "player", "巻き戻し"], "2026-07-24"),
  icon("playlist", "Playlist", "プレイリスト", "media", IconPlaylist, ["queue", "music", "再生一覧"], "2026-07-24"),
  icon("movie", "Movie", "映画", "media", IconMovie, ["film", "video", "映像"], "2026-07-23"),
  icon("photo-plus", "Add Photo", "画像を追加", "media", IconPhotoPlus, ["image", "new", "写真"], "2026-07-23"),
  icon("radio", "Radio", "ラジオ", "media", IconRadio, ["broadcast", "audio", "放送"], "2026-07-23"),
  ...originalsCatalog,
];

function original(
  slug,
  name,
  nameJa,
  category,
  tags,
  createdAt = "2026-08-09",
  batch = "001",
  family,
) {
  const item = {
    ...icon(
      slug,
      name,
      nameJa,
      category,
      pathroomOriginalIcons[slug],
      tags,
      createdAt,
      "pathroom-originals",
    ),
    batch,
  };

  return family ? { ...item, family } : item;
}

function icon(
  slug,
  name,
  nameJa,
  category,
  Icon,
  tags,
  createdAt,
  collection = "tabler",
) {
  return { slug, name, nameJa, category, collection, Icon, tags, createdAt };
}
